### ISSUE TITLE
Ability to read incoming packets from a remote machine

### ISSUE THREAD

**Issue by WHeron99** [racehub-io/f1-telemetry-client#50]
When developing a telemetry application for a remote device of mine, I find it a bit convoluted to set up a forwarding application in order to forward the telemetry packets to my second device (not running the game itself). At present, the client binds to the localhost.

Ideally, I would (personally) like the client to support reading packets from a remote sources as a potential option when constructing the client - though defaulting to only binding to localhost. 

This may be a naive approach - I haven't contributed to any public repos before - but I assume this could be implemented by passing another opt to the constructor (ie, the address we want to bind to, defaulting to 'localhost'), and the using this in the bind at index.ts:196.

**Comment by jonybur** [comment]
Merging your PR now. Thank you!
