### ISSUE TITLE
Doesn’t works or maybe i wrong something 

### ISSUE THREAD

**Issue by Joebel81** [racehub-io/f1-telemetry-client#55]
Hello to everybody,
I’m not a programmer so let me ask you sorry if you will find my issue report stupid.
I followed the indication to install the code with terminal and after that I followed the Comand line to run start but it doesn’t works.
There is someone so kindly to explain me how can use it? It is my first time on github and i don’t know too about this.
Thank you in advance!
![F38C1BCF-1D50-4D94-A5C0-9C602E34DB3F](https://user-images.githubusercontent.com/87584168/126234737-c4472ddb-ad97-44fa-89f5-0f2b532f1f1f.png)

**Comment by PrimeGoose** [comment]
When you have 'type: module' in the `package.json` file, your source code should use import syntax. When you do not have, you should use require syntax.

Adding 'type': 'module' to the `package.json` enables ES 6 modules. For more info, see [here](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling).

**Comment by jonybur** [comment]
@Joebel81  Please refer to StackOverflow for questions of this nature (e.g. https://stackoverflow.com/questions/61401475/why-is-type-module-in-package-json-file). This is a channel to report library bugs, therefore I'll close this bug. Thank you
