### ISSUE TITLE
Broadcast mode

### ISSUE THREAD

**Issue by msansoni** [racehub-io/f1-telemetry-client#56]
The following line binds the port to the localhost address, therefore prevents broadcast mode from working. Removing this line will allow both a bound to localhost and broadcast to work.
https://github.com/racehub-io/f1-telemetry-client/blob/b412ec6fc7378a7090947213ceafbd2f16f3e141/src/index.ts#L200

**Comment by jonybur** [comment]
Fixed in 0.1.24
