### ISSUE TITLE
Participant Packet has incorrect data in MP

### ISSUE THREAD

**Issue by Kiyamarak** [racehub-io/f1-telemetry-client#59]
**Describe the bug**
There is an issue with parsing Participant data packets. The data returned by the client makes no sense, violating som values. For example m_aiControlled being neither 0 nor 1

**To Reproduce**
Create a multiplayer practice lobby  and add AI.

**Expected behavior**
Values to make sense, such as being valid ranges, not cutting off drivers' names, complete information (m_yourTelemetry is missing) 

**Screenshots/Additional information**

> {
  m_header: {
    m_packetFormat: 2021,
    m_gameMajorVersion: 1,
    m_gameMinorVersion: 5,
    m_packetVersion: 1,
    m_packetId: 4,
    m_sessionUID: 3818434258042463724n,
    m_sessionTime: 450.77685546875,
    m_frameIdentifier: 32103,
    m_playerCarIndex: 19,
    m_secondaryPlayerCarIndex: 255
  },
  m_participants: [
    {
      m_aiControlled: 20,
      m_driverId: 1,
      m_teamId: 7,
      m_raceNumber: 255,
      m_nationality: 0,
      m_name: '\x00,\nHAMILTON'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 1,
      m_nationality: 1,
      m_name: '\x0F�\x00\x00M\x1BBOTTAS'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x01\x01\t�\x02\x00!\x16VERSTAPPEN'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x01\x01\x0E�\x02\x00\x0B4PEREZ'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x01\x01\x02�\b\x00\x03\x03RICCIARDO'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x016�\b\x00\x04\nNORRIS'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01\x13�\x04\x00\x12\rSTROLL'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01\r�\x04\x00\x05\x1DVETTEL'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01\x03�\x05\x00\x0EMALONSO'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01\x11�\x05\x00\x1F\x1COCON'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01:�\x01\x00\x105LECLERC'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01\x00�\x01\x007MSAINZ'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01;�\x06\x00\n\x1CGASLY'
    },
    {
      m_aiControlled: 0,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01^�\x06\x00\x16+TSUNOD'
    },
    {
      m_aiControlled: 65,
      m_driverId: 0,
      m_teamId: 0,
      m_raceNumber: 0,
      m_nationality: 0,
      m_name: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01\x06�\t\x00\x07\x1BRÄ'
    },
    {
      m_aiControlled: 73,
      m_driverId: 75,
      m_teamId: 75,
      m_raceNumber: 195,
      m_nationality: 150,
      m_name: 'NEN\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01J�\t\x00c)'
    },
    {
      m_aiControlled: 71,
      m_driverId: 73,
      m_teamId: 79,
      m_raceNumber: 86,
      m_nationality: 73,
      m_name: 'NAZZI\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01O�\x07'
    },
    {
      m_aiControlled: 0,
      m_driverId: 9,
      m_teamId: 0,
      m_raceNumber: 77,
      m_nationality: 65,
      m_name: 'ZEPIN\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01'
    },
    {
      m_aiControlled: 81,
      m_driverId: 255,
      m_teamId: 7,
      m_raceNumber: 0,
      m_nationality: 47,
      m_name: '\x1DSCHUMACHER'
    },
    {
      m_aiControlled: 0,
      m_driverId: 1,
      m_teamId: 1,
      m_raceNumber: 63,
      m_nationality: 255,
      m_name: '\x03\x00\x06\rLATIFI'
    }
  ]
}

**Comment by jonybur** [comment]
On it. Will be fixed this weekend. Thanks

**Comment by jonybur** [comment]
This is fixed on 0.1.26
