### ISSUE TITLE
No data in practice sessions. 

### ISSUE THREAD

**Issue by iamisti** [racehub-io/f1-telemetry-client#71]
**Describe the bug**
Basically if you'r doing a race, you do have the telemtry outputting nicely. 
But as soon as you jump into a practice session, there is no data coming out of the listeners.

**Comment by jonybur** [comment]
Hey @iamisti I noticed you closed this issue. Sorry I have not been able to put much time onto the project lately. Has this been resolved by you?

**Comment by iamisti** [comment]
Problem solved, it was on my end.
