### ISSUE TITLE
LobbyInfo doesn't have player user names in multiplayer mode

### ISSUE THREAD

**Issue by iamisti** [racehub-io/f1-telemetry-client#73]
All players have 'Player' username in multiplayer mode. 
Can you please fix this? 

If it's an AI, then the username comes through, but in case of a non-ai player, the username is not populated correctly. As I said, everyone has 'Player' as his username which is clearly wrong.

**Comment by iamisti** [comment]
@jonybur pls respond if you can as soon as you can. I can't wait 1 week for a response :)

**Comment by iamisti** [comment]
damn, but then the telemetry data is kind of useless. Wonder why they did it this way.

**Comment by codegefluester** [comment]
> but then the telemetry data is kind of useless

Well, that kind of depends on your specific use-case. With some manual post-processing of the data it should be possible to have the real names but that would essentially require a human to enter the names manually.

Anyways, nothing @jonybur or anyone can do about this for as long as Codemasters doesn't provide a solution for this. You can always contact Codemasters and add your voice to the list of other developers who flagged the same issue.
