### ISSUE TITLE
Connected and Disconnected events

### ISSUE THREAD

**Issue by iamisti** [racehub-io/f1-telemetry-client#75]
I need events that tells me if the telemetry client is connected or when the telemetry client goes to a disconnected state.

There is a difference, because when you hit esc in the game, the telemetry feed pauses.
But when you exit from a session, we should have a disconnect event firing.

To add to this, gameIsPaused property is not mapped correctly in the PacketSessionData object. It's value is always 0, even when i pause the game.

@jonybur

**Comment by msansoni** [comment]
Unfortunately with this library solely parsing the packets, any game logic or additional state information (e.g. paused state) is a feature request for the game rather than this library.
