### ISSUE TITLE
Fastest lap event not firing

### ISSUE THREAD

**Issue by chaseconey** [racehub-io/f1-telemetry-client#78]
**Describe the bug**
The Fastest Lap event doesn't seem to be firing.

**To Reproduce**

**Configuration:**

IP: 127.0.0.1
Port: 20777
Send Rate: 20Hz
Format: 2021

**Steps:**

- Watch event packets
- Spectate a race
- Watch until someone gets the fastest lap

**Expected behavior**
When the fastest lap is broken, I expect to see a `FTLP` event fire.

**Comment by visualroam** [comment]
Hello, 

this is still the case and is there any intention that this will be fixed soon?
It a normal event nothing special and should be fixable fast.

This is still the case (with F122 UDP Settings)

**Comment by msansoni** [comment]
Unfortunately with this library solely parsing the packets, any game logic bugs are an issue with the game rather than this library.
