### ISSUE TITLE
Help Requested

### ISSUE THREAD

**Issue by BrokenHypocrite** [racehub-io/f1-telemetry-client#80]
Hi,

I am attempting to create a react web app for use in Twitch streams (using OBS). I am fairly new to JS and React and am having a lot of trouble figuring out how to actually parse the telemetry information to my app. I have tried including the f1-telemetry-client a number of ways but have not had any luck. I was hoping someone would be kind enough to post an example of a simple react app, or even just html page updating a leaderboard via the packets. This would be enough to get me started. Ultimately I am trying to created a dynamic web app that will show information like the leaderboard (with options to show/hide current tires, age of tires, interval to leader, interval to next driver ahead, DRS activation, fastest lap, penalties, number of pitstops, DNF, DNS, etc), as well as current and project weather information, average pit stop time, driver vs driver interval (pick drivers to compare from drop down menu), and more. I will be making my own project opensource for other F1 2021 Streamers to use if I can ever get it to work. Any help will be greatly appreciated!

Thanks for your time,
Bryan

**Comment by msansoni** [comment]
@BrokenHypocrite given this isnt a specific issue with the code on the library I’m going to close the issue. Probably best you raise this question on StackOverflow or the EA forums for the UDP someone will likely help you there.
