### ISSUE TITLE
Special characters in driver names

### ISSUE THREAD

**Issue by iamisti** [racehub-io/f1-telemetry-client#86]
**Describe the bug**
In multiplayer it's more enhanced but even in solo player mode, the 2022 udp telemetry gives me special characters in front of the driver names in the participation data feed.
Sometimes its more extreem with a lots of special characters prefixing a name.

**To Reproduce**
Go to multiplayer game or solo game and check participation data.

**Expected behavior**
No special characters in names

**Screenshots/Additional information**
Solo and multiplayer screenshots of the data:
![image](https://user-images.githubusercontent.com/4672916/178134710-5f2c3609-6337-4198-ab93-edd5fd6e01a7.png)
![image](https://user-images.githubusercontent.com/4672916/178134765-885ce086-e0dc-4942-b445-285d726157a9.png)
![image](https://user-images.githubusercontent.com/4672916/178134773-02131d25-6457-4bed-9777-da94027bd7b3.png)

**Comment by z0mt3c** [comment]
that was the issue i tried to address with #83 - but i wasnt able to reproduce it again yesterday

**Comment by z0mt3c** [comment]
Had another look into it (telemetry 2022, v1.05, steam, simple grand prix), still seems to be faulty...

participants data parsed by f1-telemetry-client:
`{
  "m_header": {
    "m_packetFormat": 2022,
    "m_gameMajorVersion": 1,
    "m_gameMinorVersion": 5,
    "m_packetVersion": 1,
    "m_packetId": 4,
    "m_sessionUID": "4698597533777907588",
    "m_sessionTime": 9.827771186828613,
    "m_frameIdentifier": 415,
    "m_playerCarIndex": 19,
    "m_secondaryPlayerCarIndex": 255
  },
  "m_participants": [
    {
      "m_aiControlled": 20,
      "m_driverId": 1,
      "m_networkId": 19,
      "m_teamId": 255,
      "m_myTeam": 4,
      "m_raceNumber": 0,
      "m_nationality": 18,
      "m_name": "\rSTROLL",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 58,
      "m_teamId": 255,
      "m_myTeam": 1,
      "m_raceNumber": 0,
      "m_nationality": 16,
      "m_name": "5LECLERC",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 59,
      "m_teamId": 255,
      "m_myTeam": 6,
      "m_raceNumber": 0,
      "m_nationality": 10,
      "m_name": "\u001cGASLY",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 15,
      "m_teamId": 255,
      "m_myTeam": 9,
      "m_raceNumber": 0,
      "m_nationality": 77,
      "m_name": "\u001bBOTTAS",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 50,
      "m_teamId": 255,
      "m_myTeam": 0,
      "m_raceNumber": 0,
      "m_nationality": 63,
      "m_name": "\nRUSSELL",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 11,
      "m_teamId": 255,
      "m_myTeam": 7,
      "m_raceNumber": 0,
      "m_nationality": 20,
      "m_name": "\u0015MAGNUSSEN",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 17,
      "m_teamId": 255,
      "m_myTeam": 5,
      "m_raceNumber": 0,
      "m_nationality": 31,
      "m_name": "\u001cOCON",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 54,
      "m_teamId": 255,
      "m_myTeam": 8,
      "m_raceNumber": 0,
      "m_nationality": 4,
      "m_name": "\nNORRIS",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 62,
      "m_teamId": 255,
      "m_myTeam": 3,
      "m_raceNumber": 0,
      "m_nationality": 23,
      "m_name": "PALBON",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 63,
      "m_teamId": 255,
      "m_myTeam": 3,
      "m_raceNumber": 0,
      "m_nationality": 6,
      "m_name": "\rLATIFI",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 81,
      "m_teamId": 255,
      "m_myTeam": 7,
      "m_raceNumber": 0,
      "m_nationality": 47,
      "m_name": "\u001dSCHUMACHER",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 2,
      "m_teamId": 255,
      "m_myTeam": 8,
      "m_raceNumber": 0,
      "m_nationality": 3,
      "m_name": "\u0003RICCIARDO",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 14,
      "m_teamId": 255,
      "m_myTeam": 2,
      "m_raceNumber": 0,
      "m_nationality": 11,
      "m_name": "4PÉREZ",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 80,
      "m_teamId": 255,
      "m_myTeam": 9,
      "m_raceNumber": 0,
      "m_nationality": 24,
      "m_name": "\u000fGUANYU",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 94,
      "m_teamId": 255,
      "m_myTeam": 6,
      "m_raceNumber": 0,
      "m_nationality": 22,
      "m_name": "+TSUNODA",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 7,
      "m_teamId": 255,
      "m_myTeam": 0,
      "m_raceNumber": 0,
      "m_nationality": 44,
      "m_name": "\nHAMILTON",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 0,
      "m_teamId": 255,
      "m_myTeam": 1,
      "m_raceNumber": 0,
      "m_nationality": 55,
      "m_name": "MSAINZ",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 3,
      "m_teamId": 255,
      "m_myTeam": 5,
      "m_raceNumber": 0,
      "m_nationality": 14,
      "m_name": "MALONSO",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 1,
      "m_networkId": 13,
      "m_teamId": 255,
      "m_myTeam": 4,
      "m_raceNumber": 0,
      "m_nationality": 5,
      "m_name": "\u001dVETTEL",
      "m_yourTelemetry": 0
    },
    {
      "m_aiControlled": 1,
      "m_driverId": 0,
      "m_networkId": 9,
      "m_teamId": 255,
      "m_myTeam": 2,
      "m_raceNumber": 0,
      "m_nationality": 33,
      "m_name": "\u0016VERSTAPPEN",
      "m_yourTelemetry": 0
    }
  ]
}`

raw:

` {
    "type": "Buffer",
    "data": [
      230, 7, 1, 5, 1, 4, 132, 207, 91, 15, 144, 197, 52, 65, 141, 62, 29, 65, 159, 1, 0, 0, 19, 255, 20, 1, 19, 255, 4, 0, 18, 13, 83, 84, 82, 79, 76, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 58, 255, 1, 0, 16, 53, 76, 69, 67, 76, 69, 82, 67, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 59, 255, 6, 0, 10, 28, 71, 65, 83, 76, 89, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 15, 255, 9, 0, 77, 27, 66, 79, 84, 84, 65, 83, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 50, 255, 0, 0, 63, 10, 82, 85, 83, 83, 69, 76, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 11, 255, 7, 0, 20, 21, 77, 65, 71, 78, 85, 83, 83, 69, 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 17, 255, 5, 0, 31, 28, 79, 67, 79, 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 54, 255, 8, 0, 4, 10, 78, 79, 82, 82, 73, 83, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 62, 255, 3, 0, 23, 80, 65, 76, 66, 79, 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 63, 255, 3, 0, 6, 13, 76, 65, 84, 73, 70, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 81, 255, 7, 0, 47, 29, 83, 67, 72, 85, 77, 65, 67, 72, 69, 82, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 255, 8, 0, 3, 3, 82, 73, 67, 67, 73, 65, 82, 68, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 14, 255, 2, 0, 11, 52, 80, 195, 137, 82, 69, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 80, 255, 9, 0, 24, 15, 71, 85, 65, 78, 89, 85, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 94, 255, 6, 0, 22, 43, 84, 83, 85, 78, 79, 68, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 7, 255, 0, 0, 44, 10, 72, 65, 77, 73, 76, 84, 79, 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 255, 1, 0, 55, 77, 83, 65, 73, 78, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 3, 255, 5, 0, 14, 77, 65, 76, 79, 78, 83, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 13, 255, 4, 0, 5, 29, 86, 69, 84, 84, 69, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 9, 255, 2, 0, 33, 22, 86, 69, 82, 83, 84, 65, 80, 80, 69, 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 255, 255, 255, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ]
}`

**Comment by iamisti** [comment]
@z0mt3c you mean you fixed it in your fork?

**Comment by z0mt3c** [comment]
@iamisti yeah, doesnt follow the specs but seems to work... 

@z0mt3c/racehub-io-f1-telemetry-client@0.2.7-7
