### ISSUE TITLE
'Parser' only refers to a type, but is being used as a namespace here.

### ISSUE THREAD

**Issue by ivomarsan** [racehub-io/f1-telemetry-client#91]
**Describe the bug**
I tried to run the repository code using `yarn start` and I receive the error TS2702

**To Reproduce**
1. I'd cloned the repository and enter on cloned folder
2. I had run `yarn` to install dependencies
3. I put `yarn start` to build and run `tsc`

**Expected behavior**
I just expect to run without errors

**Screenshots/Additional information**
![image](https://user-images.githubusercontent.com/5050885/186224175-9c4d6373-c838-4b26-b78f-cbabec708428.png)

**Comment by msansoni** [comment]
I'm unable to recreate this issue, with both `yarn` and `npm` are you able to provide more details on the system/environment you're on.
