### ISSUE TITLE
Incorrect packet types

### ISSUE THREAD

**Issue by alanqthomas** [racehub-io/f1-telemetry-client#92]
**Describe the bug**
The [packet type definitions](https://github.com/racehub-io/f1-telemetry-client/blob/master/src/parsers/packets/types.ts) are incorrect.

For example, in game version 2022, the fields for sector 1 and 2 times are `m_sector1TimeInMS` and `m_sector2TimeInMS`, but the type definitions have them as `m_sector1Time:` `m_sector2Time`.

I've been getting around this by using `@ts-expect-error` annotations for the time being and just using the correct field names as defined in the actual parser.

**Expected behavior**
Packet type definitions should reflect the data being received, which can be different based on the game version.

**Comment by msansoni** [comment]
Same as #72 - type definitions need switching based on game version (year)
